[package]
name = "lumen-core"
description = "Platform-independent parts of Lumen: UI, rendering, OS knowledge, file systems, Linux boot logic"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
fontdue = { version = "0.9.4", default-features = false, features = ["hashbrown"] }
libm = "0.2.16"
miniz_oxide = { version = "0.8", default-features = false, features = ["with-alloc"] }
ruzstd = { version = "0.8", default-features = false }

[dev-dependencies]
sha2 = "0.10"
